### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by RonanCodes** [RonanC/WordCloud#1]
**Part 1 - Input**
- [x] Read data in from file
- [x] Read data in from url
- [x] Add all words to hashmap
- [x] Perform analysis on data (regex)
- [x] Remove stop words
- [x] Count valid words

**Part 2 - Graphics**
- [x] Draw words with Java 2D API
- [x] Refactor from one class into multiple packages and classes
- [x] Scale max count so that it is always the same size relative

**Part 3 - Ref**
- [x] Check out JSoup
- [x] Check out cue.lang

**Part 4 - Final**
- [x] Complete ReadMe
- [x] Ant
- [x] Java Docs (comments)
- [x] Jar
- [x] zip archive
- [x] Make sure design patterns are used (singleton, builder, adapter, etc)
- [x] Jar Executable
- [x] UML
- [x] Unit Tests/Suites (10/15 of them, not 50)
- [x] JavaDoc Comments

**Part 5 - Structure Check**
- [x] Interfaces
- [x] Loose coupling
- [x] Abstraction and encapsulation
- [x] Multiple classes
- [ ] Builder Pattern
- [x] Singleton Pattern
- [x] Factory Pattern

**Part 6 - Additions**
- [x] Incorporate greedy spiral algorithm
- [ ] Add as Java Applet in web page?
- [x] Play with fonts, colours and log (for count)
- [x] Add a gui with radio buttons and inputs with validation
- [x] Add a loading (progress) bar to the JPanel
- [ ] Program Icon

**Part 7 - Tests**
- [x] Graphics
- [x] IO
- [x] Runner

**Comment by RonanCodes** [comment]
Finished part one, read in from file and analyse.
URL read in still left to do.

**Comment by RonanCodes** [comment]
URL reading working
Incorporated Jsoup
Checked our cue.lang (a bit too complex, but useful) (cue.lang is the algorithm used in Wordle)
Finished ReadMe

**Comment by RonanCodes** [comment]
Added the greedy spiral algorithm, although it could use adjustments.
Added random colours and fonts (no log).
Code needs to be cleaned up, refactored and design patterns implemented.
Also executable and Java Docs complete.

**Comment by RonanCodes** [comment]
Refactoring done.
Added more items to the GUI

**Comment by RonanCodes** [comment]
Progress indicator and Scaling complete.

**Comment by RonanCodes** [comment]
Ant, Jar and Docs complete.
Code commented.

**Comment by RonanCodes** [comment]
Moved code into more general classes and methods as to allow for a loosely coupled design.
Abstracted and encapsulated code where possible.
DataReader interface added.
Singleton Factory created for DataReader, create url and file data readers. (no adapter, builder, strategy or decorator).

**Comment by RonanCodes** [comment]
Major tasks complete.
Project submitted.
